### PR TITLE
Added simple implementation

### PR DESCRIPTION
**Pull request by raymayemir**
Hi! This is my first pull request in go community! 
If you approve, I will change the description and resubmit. Thanks 🙂

### CODE REVIEW

**Comment by raymayemir** [comment]
@Fenny I had an idea to put the user in locales, but received an empty value in requests
in tests, if i'm put it directly in `c.Fasthttp.SetUserValue()` then i got them. 
How to do it right?

**Comment by Fenny** [comment]
Sorry for the late response, I will take a complete look tomorrow morning!

**Comment by raymayemir** [comment]
> Sorry for the late response, I will take a complete look tomorrow morning!

It’s ok, Looking ahead I think need to improve the model and make it more flexible

**Comment by Fenny** [comment]
@raymayemir, I just pushed `v0.0.1`. I think it is more aligned along with the other middlewares, what do you think?

**Comment by raymayemir** [comment]
@Fenny It looks cool! You decided to do all the options, but I wanted to come to this step by step 😄 and what about list of endpoints that doesn't require auth?

**Comment by raymayemir** [comment]
@Fenny It is enough to use Middleware after paths like you example. cool

**Comment by Fenny** [comment]
I currently added `fiberJWT "github.com/gofiber/jwt"` to avoid the name conflict with the official `jwt` package, this might be something that could be a little bit cleaner. I will keep this PR open for discussion.

**Pull request closed without merging**
