### PR TITLE
Implementing JWKs

### PR DESCRIPTION
**Pull request by shytikov**
Looks like a lot of changes, but I've tried to structure it logically:

* code from `jwt.go` was split – `Config` were moved to `config.go` and the main middleware call was moved to `main.go`;
* added `jwks.go` file which contains code from `https://github.com/MicahParks/keyfunc`
* rest are support files from `keyfunc`.

I haven't modified logic from the initial `jwt.go`. All configurations which were added are optional, and `jwks` will kick in only if `KeySetUrl` will be provided. That will replace the original `keyfunc` with the one that is able to work with `jwks`.

I believe I could get away with smaller changes if I would reference `https://github.com/MicahParks/keyfunc` directly. But that would bring additional unused legacy dependencies to this middleware and to the rest of the projects which will be using it, so I decided to copy files instead.

I have tested it on my JWKs server, and it works (on my machine :), including background updates of the keys.

I'm open to any suggestions that would make this PR better. Many thanks in advance!

### CODE REVIEW

**Comment by ReneWerner87** [comment]
Thx, please provide unittests and a part in the readme.

**Comment by shytikov** [comment]
@ReneWerner87 on it!

**Comment by shytikov** [comment]
@ReneWerner87 could you please check is it `LGTM`? 

I can continue covering with tests these pieces of code. But I am afraid that I will delay the code and I'm also forced into refactoring as I write the tests, so I wanted to put a comma somewhere.

**Comment by shytikov** [comment]
ping @ReneWerner87 :)

**Comment by ReneWerner87** [comment]
Jo, sure..  Will check it on the weekend) currently to much other stuff)

**Comment by shytikov** [comment]
Thank you! :)

**Review by ReneWerner87 — APPROVED** [review]

**Comment by ReneWerner87** [comment]
@shytikov can you please correct the three comments of the automated test and the linter

**Comment by shytikov** [comment]
On it! @ReneWerner87  :)

**Comment by shytikov** [comment]
@ReneWerner87 Hopefully now everything shoudl be fine!

**Pull request merged**
